# Generated by Django 4.0.2 on 2022-07-11 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazin', '0002_rename_pelcon_files'),
    ]

    operations = [
        migrations.AddField(
            model_name='files',
            name='broj',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
