# Generated by Django 4.0.2 on 2022-07-12 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('magazin', '0003_files_broj'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='files',
            options={'verbose_name': 'File', 'verbose_name_plural': 'Files'},
        ),
    ]
