# Generated by Django 4.0.2 on 2022-08-25 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('magazin', '0004_alter_files_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='files',
            options={'verbose_name': 'Magazin Izdanje', 'verbose_name_plural': 'Magazin Izdanja'},
        ),
    ]
