# Generated by Django 4.0.2 on 2022-08-10 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Planeri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ime', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='planeri/pdfs/')),
                ('cover', models.ImageField(upload_to='planeri/covers/')),
            ],
            options={
                'verbose_name': 'Planer',
                'verbose_name_plural': 'Planeri',
            },
        ),
    ]
