# Generated by Django 4.0.2 on 2022-08-10 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zatrenere', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lekarski',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ime', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='lekarski/pdfs/')),
                ('tip', models.CharField(choices=[('pdf', 'pdf'), ('word', 'word')], default='pdf', max_length=5)),
                ('cover', models.ImageField(upload_to='lekarski/covers/')),
            ],
            options={
                'verbose_name': 'Lekarski',
                'verbose_name_plural': 'Lekarski',
            },
        ),
    ]
