# Generated by Django 4.0.2 on 2022-08-11 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zatrenere', '0002_lekarski'),
    ]

    operations = [
        migrations.CreateModel(
            name='Uplatnice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ime', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='uplatnice/pdfs/')),
                ('cover', models.ImageField(upload_to='uplatnice/covers/')),
            ],
            options={
                'verbose_name': 'Uplatnice',
                'verbose_name_plural': 'Uplatnice',
            },
        ),
    ]
