# Generated by Django 4.0.2 on 2022-07-17 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Knjige',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naslov', models.CharField(max_length=100)),
                ('autor', models.CharField(default='', max_length=100)),
                ('godina', models.IntegerField()),
                ('cover', models.ImageField(default='all_domaci.jpeg', upload_to='knjige/covers/')),
            ],
            options={
                'verbose_name': 'Knjiga',
                'verbose_name_plural': 'Knjige',
            },
        ),
    ]
