# Generated by Django 4.0.2 on 2022-07-17 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edukacija', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='knjige',
            name='pdf',
            field=models.FileField(default='', upload_to='edukacija/knjige/'),
            preserve_default=False,
        ),
    ]
