# Generated by Django 4.0.2 on 2022-07-17 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edukacija', '0002_knjige_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knjige',
            name='pdf',
            field=models.FileField(upload_to='knjige/pdf'),
        ),
    ]
