# Generated by Django 4.0.2 on 2022-08-16 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edukacija', '0003_alter_knjige_pdf'),
    ]

    operations = [
        migrations.CreateModel(
            name='FibaAssist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('broj', models.IntegerField()),
                ('pdf', models.FileField(upload_to='FIBA/pdf')),
                ('cover', models.ImageField(default='all_domaci.jpeg', upload_to='FIBA/covers/')),
            ],
            options={
                'verbose_name': 'Fiba Assist',
                'verbose_name_plural': 'Fiba Assist',
            },
        ),
    ]
