# Generated by Django 4.0.2 on 2022-08-16 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edukacija', '0004_fibaassist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fibaassist',
            name='broj',
            field=models.CharField(max_length=3),
        ),
    ]
