# Generated by Django 4.0.2 on 2022-08-16 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edukacija', '0005_alter_fibaassist_broj'),
    ]

    operations = [
        migrations.CreateModel(
            name='StrucneTeme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autor', models.CharField(max_length=70)),
                ('naslov', models.CharField(max_length=100)),
                ('pdf', models.FileField(upload_to='strucne')),
            ],
            options={
                'verbose_name': 'Strucne Teme',
                'verbose_name_plural': 'Strucne Teme',
            },
        ),
    ]
