# Generated by Django 4.0.2 on 2022-08-17 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edukacija', '0006_strucneteme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strucneteme',
            name='naslov',
            field=models.CharField(max_length=150),
        ),
    ]
