# Generated by Django 4.0.2 on 2022-08-17 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edukacija', '0007_alter_strucneteme_naslov'),
    ]

    operations = [
        migrations.CreateModel(
            name='Linkovi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('link', models.URLField()),
                ('cover', models.ImageField(default='all_domaci.jpeg', upload_to='linkovi/')),
            ],
            options={
                'verbose_name': 'Linkovi',
                'verbose_name_plural': 'Linkovi',
            },
        ),
        migrations.CreateModel(
            name='LinkoviPDF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('pdf', models.FileField(upload_to='linkovi/pdf')),
                ('cover', models.ImageField(default='link_cover3.png', upload_to='linkovi/cover')),
            ],
            options={
                'verbose_name': 'Linkovi PDF',
                'verbose_name_plural': 'Linkovi PD',
            },
        ),
    ]
