# Generated by Django 4.0.2 on 2022-08-17 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edukacija', '0008_linkovi_linkovipdf'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='linkovipdf',
            options={'verbose_name': 'Linkovi PDF', 'verbose_name_plural': 'Linkovi PDF'},
        ),
        migrations.AlterField(
            model_name='linkovipdf',
            name='cover',
            field=models.ImageField(default='ukts/img/link_cover3.png', upload_to='linkovi/cover'),
        ),
    ]
