# Generated by Django 4.0.2 on 2022-08-17 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edukacija', '0009_alter_linkovipdf_options_alter_linkovipdf_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linkovipdf',
            name='cover',
            field=models.ImageField(default='link_cover3.png', upload_to='linkovi/cover'),
        ),
    ]
