# Generated by Django 4.0.2 on 2022-09-18 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edukacija', '0010_alter_linkovipdf_cover'),
    ]

    operations = [
        migrations.CreateModel(
            name='Knjiga_Promocija',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_page', models.ImageField(default='all_domaci.jpeg', upload_to='knjige_promo/klinika/')),
                ('slika_slider1', models.ImageField(default='all_domaci.jpeg', upload_to='knjige_promo/klinika/')),
                ('slika_slider2', models.ImageField(default='all_domaci.jpeg', upload_to='knjige_promo/klinika/')),
                ('slika_slider3', models.ImageField(default='all_domaci.jpeg', upload_to='knjige_promo/klinika/')),
                ('slika_slider4', models.ImageField(default='all_domaci.jpeg', upload_to='knjige_promo/klinika/')),
                ('naslov', models.CharField(max_length=150)),
                ('autor', models.CharField(max_length=100)),
                ('pdf', models.FileField(upload_to='promoBook/pdf')),
            ],
            options={
                'verbose_name': 'Knjige promocija i najava',
                'verbose_name_plural': 'Knjige promocija i najava',
            },
        ),
    ]
