# Generated by Django 4.0.2 on 2022-08-10 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClanUO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ime', models.CharField(max_length=100)),
                ('funkcija', models.CharField(choices=[('Predsednik', 'Predsednik'), ('Generalni sekretar', 'Generalni sekretar'), ('Član upravnog odbora', 'Upravni odbor')], default='uo', max_length=100)),
                ('linkedin', models.URLField(blank=True)),
                ('twitter', models.URLField(blank=True)),
                ('facebook', models.URLField(blank=True)),
                ('instagram', models.URLField(blank=True)),
                ('slika', models.ImageField(default='default.png', upload_to='upravni_odbor/')),
            ],
            options={
                'verbose_name': 'Clan UO',
                'verbose_name_plural': 'Clanovi UO',
            },
        ),
    ]
