# Generated by Django 4.0.2 on 2022-08-10 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onama', '0004_pravilnik'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pravilnik',
            options={'verbose_name': 'Pravilnik', 'verbose_name_plural': 'Pravilnik'},
        ),
    ]
