# Generated by Django 4.0.2 on 2022-08-10 19:15

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onama', '0005_alter_pravilnik_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kodeks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('body', ckeditor_uploader.fields.RichTextUploadingField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10)),
                ('image', models.ImageField(upload_to='kodeks/')),
            ],
            options={
                'verbose_name': 'Pravilnik',
                'verbose_name_plural': 'Pravilnik',
            },
        ),
    ]
