# Generated by Django 4.0.2 on 2022-08-10 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onama', '0006_kodeks'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kodeks',
            options={'verbose_name': 'Kodeks', 'verbose_name_plural': 'Kodeks'},
        ),
    ]
