# Generated by Django 4.0.2 on 2022-08-14 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onama', '0009_faq'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='image',
            field=models.ImageField(default='default.png', upload_to='faq/'),
        ),
    ]
