# Generated by Django 4.0.2 on 2022-08-14 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onama', '0010_faq_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faq',
            name='image',
        ),
    ]
