# Generated by Django 4.0.2 on 2022-08-15 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onama', '0011_remove_faq_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faq',
            options={'ordering': ['id']},
        ),
    ]
