# Generated by Django 4.0.2 on 2022-07-14 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Klub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ime_kluba', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Trener',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ime', models.CharField(max_length=100)),
                ('licenca', models.CharField(blank=True, max_length=100, null=True)),
                ('telefon', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('region', models.CharField(choices=[('Vojvodina', 'Vojvodina'), ('Beograd', 'Beograd'), ('Istočna Srbija', 'Istočna Srbija'), ('Zapadna Srbija', 'Zapadna Srbija'), ('Juzna Srbija', 'Juzna Srbija'), ('Republika Srpska', 'Republika Srpska'), ('Inostranstvo', 'Inostranstvo')], max_length=200, null=True)),
                ('datum_rodjenja', models.DateField()),
                ('slika', models.ImageField(default='default.png', null=True, upload_to='treneri_profil')),
                ('klub', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='treneri.klub')),
            ],
        ),
    ]
