# Generated by Django 4.0.4 on 2022-06-29 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treneri', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trener',
            name='godiste',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trener',
            name='region',
            field=models.CharField(choices=[('Vojvodina', 'Vojvodina'), ('Beograd', 'Beograd'), ('Istočna Srbija', 'Istočna Srbija'), ('Zapadna Srbija', 'Zapadna Srbija'), ('Juzna Srbija', 'Juzna Srbija'), ('Republika Srpska', 'Republika Srpska')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='trener',
            name='ime',
            field=models.CharField(default='null', max_length=100),
            preserve_default=False,
        ),
    ]
