# Generated by Django 4.0.2 on 2022-07-15 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treneri', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trener',
            name='region',
            field=models.CharField(blank=True, choices=[('Vojvodina', 'Vojvodina'), ('Beograd', 'Beograd'), ('Istočna Srbija', 'Istočna Srbija'), ('Zapadna Srbija', 'Zapadna Srbija'), ('Juzna Srbija', 'Juzna Srbija'), ('Republika Srpska', 'Republika Srpska'), ('Inostranstvo', 'Inostranstvo')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='trener',
            name='slika',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to='treneri_profil'),
        ),
    ]
