# Generated by Django 4.0.4 on 2022-06-29 12:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treneri', '0002_trener_godiste_trener_region_alter_trener_ime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trener',
            name='godiste',
        ),
        migrations.AddField(
            model_name='trener',
            name='datum_rodjenja',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
