# Generated by Django 4.0.2 on 2022-08-25 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treneri', '0002_alter_trener_region_alter_trener_slika'),
    ]

    operations = [
        migrations.CreateModel(
            name='UktsTrener',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ime', models.CharField(max_length=50)),
                ('prezime', models.CharField(max_length=50)),
                ('licenca', models.CharField(blank=True, max_length=50, null=True)),
                ('boja', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
