# Generated by Django 4.0.2 on 2022-07-14 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zip_import', models.FileField(blank=True, upload_to='galleries')),
                ('tip', models.CharField(choices=[('bcb', 'Beogradska Kosarkaska Klinika'), ('td', 'Trenerski Dani')], default='bcb', max_length=50)),
                ('godina', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Klinike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tip', models.CharField(choices=[('bcb', 'Beogradska Kosarkaska Klinika'), ('td', 'Trenerski Dani')], default='bcb', max_length=50)),
                ('predavac', models.CharField(max_length=100)),
                ('tema', models.CharField(default='', max_length=100)),
                ('godina', models.IntegerField()),
                ('link', models.URLField()),
                ('cover', models.ImageField(default='all_domaci.jpeg', upload_to='klinike/covers/')),
            ],
            options={
                'verbose_name': 'Klinika',
                'verbose_name_plural': 'Klinike',
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tip', models.CharField(choices=[('bcb', 'Beogradska Kosarkaska Klinika'), ('td', 'Trenerski Dani')], default='bcb', max_length=50)),
                ('godina', models.CharField(max_length=4)),
                ('slika', models.ImageField(upload_to='slika_upload_location')),
                ('naslov', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'verbose_name': 'Foto',
                'verbose_name_plural': 'Fotos',
            },
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, db_index=True)),
                ('file', models.ImageField(upload_to='galleries')),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='klinike.basegallery')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
