# Generated by Django 4.0.2 on 2022-08-16 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BCB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('godina', models.CharField(max_length=4)),
            ],
            options={
                'verbose_name': 'bcb',
                'verbose_name_plural': 'bcb',
            },
        ),
        migrations.CreateModel(
            name='Klinike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('predavac', models.CharField(max_length=100)),
                ('tema', models.CharField(default='', max_length=100)),
                ('godina', models.IntegerField()),
                ('link', models.URLField()),
                ('cover', models.ImageField(default='all_domaci.jpeg', upload_to='klinike/covers/')),
            ],
            options={
                'verbose_name': 'Klinika',
                'verbose_name_plural': 'Klinike',
            },
        ),
        migrations.CreateModel(
            name='TD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('godina', models.CharField(max_length=4)),
            ],
            options={
                'verbose_name': 'td',
                'verbose_name_plural': 'td',
            },
        ),
        migrations.CreateModel(
            name='TrenerskiDani',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('predavac', models.CharField(max_length=100)),
                ('tema', models.CharField(default='', max_length=100)),
                ('godina', models.IntegerField()),
                ('link', models.URLField()),
                ('cover', models.ImageField(default='all_domaci.jpeg', upload_to='klinike/covers/')),
            ],
            options={
                'verbose_name': 'Trenerski Dan',
                'verbose_name_plural': 'Trenerski Dani',
            },
        ),
        migrations.CreateModel(
            name='SlikeTD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slika', models.ImageField(upload_to='td/slike/')),
                ('trenerski_dan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='klinike.td')),
            ],
        ),
        migrations.CreateModel(
            name='SlikeBCB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slika', models.ImageField(upload_to='bcb/slike/')),
                ('klinika', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='klinike.bcb')),
            ],
        ),
    ]
