# Generated by Django 4.0.2 on 2022-08-16 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('klinike', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='klinike',
            options={'verbose_name': 'Klinika video', 'verbose_name_plural': 'Klinike video'},
        ),
        migrations.AlterModelOptions(
            name='trenerskidani',
            options={'verbose_name': 'Trenerski Dan video', 'verbose_name_plural': 'Trenerski Dani video'},
        ),
    ]
