# Generated by Django 4.0.2 on 2022-07-14 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('klinike', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='galleryimage',
            name='gallery',
        ),
        migrations.DeleteModel(
            name='BaseGallery',
        ),
        migrations.DeleteModel(
            name='GalleryImage',
        ),
    ]
