# Generated by Django 4.0.2 on 2022-08-18 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('klinike', '0002_alter_klinike_options_alter_trenerskidani_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='klinike',
            options={'ordering': ('-godina',)},
        ),
    ]
