# Generated by Django 4.0.2 on 2022-08-07 18:16

from django.db import migrations, models
import klinike.models


class Migration(migrations.Migration):

    dependencies = [
        ('klinike', '0002_remove_galleryimage_gallery_delete_basegallery_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='slika',
            field=models.ImageField(upload_to=klinike.models.slika_upload_location),
        ),
    ]
