# Generated by Django 4.0.2 on 2022-08-25 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('klinike', '0003_alter_klinike_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='klinike',
            options={'ordering': ('-godina',), 'verbose_name': 'Klinika video', 'verbose_name_plural': 'Klinike video'},
        ),
    ]
