# Generated by Django 4.0.2 on 2022-09-10 23:09

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('klinike', '0004_alter_klinike_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='BCB_Promocija',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('godina', models.CharField(max_length=4)),
                ('datum_odrzavanja', models.DateField()),
                ('promo_video', models.URLField()),
                ('slika_landing_page', models.ImageField(default='all_domaci.jpeg', upload_to='bcb_promo/klinika/')),
                ('poruka_landing_page', ckeditor_uploader.fields.RichTextUploadingField()),
                ('poruka_promo_page', ckeditor_uploader.fields.RichTextUploadingField()),
            ],
            options={
                'verbose_name': 'Klinika promocija i najava',
                'verbose_name_plural': 'Klinike promocija i najava',
                'ordering': ('-godina',),
            },
        ),
        migrations.CreateModel(
            name='BCB_Predavac',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('predavac', models.CharField(max_length=100)),
                ('tema', models.CharField(default='', max_length=100)),
                ('slika_promo_page', models.ImageField(default='all_domaci.jpeg', upload_to='bcb_promo/predavaci/')),
                ('slika_promo_slider', models.ImageField(default='all_domaci.jpeg', upload_to='bcb_promo/predavaci/')),
                ('bcb_promocija', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='klinike.bcb_promocija')),
            ],
        ),
    ]
