# Generated by Django 4.0.2 on 2022-09-10 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('klinike', '0005_bcb_promocija_bcb_predavac'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bcb_predavac',
            options={'verbose_name': 'BCB Predavač', 'verbose_name_plural': 'BCB Predavači'},
        ),
    ]
