# Generated by Django 4.0.2 on 2022-09-18 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('klinike', '0006_alter_bcb_predavac_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bcb_predavac',
            options={'verbose_name': 'BCB Predavač promocija', 'verbose_name_plural': 'BCB Predavači promocija'},
        ),
        migrations.AlterModelOptions(
            name='bcb_promocija',
            options={'ordering': ('-godina',), 'verbose_name': 'BCB promocija i najava', 'verbose_name_plural': 'BCB promocija i najava'},
        ),
        migrations.AlterField(
            model_name='bcb_promocija',
            name='datum_odrzavanja',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bcb_promocija',
            name='promo_video',
            field=models.URLField(blank=True),
        ),
    ]
